# Generated by Django 2.2.1 on 2019-05-17 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sobre_nome', models.CharField(max_length=200)),
                ('idade', models.TextField()),
                ('cpf', models.TextField()),
                ('sexo', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_nasc', models.DateTimeField(blank=True, null=True)),
                ('dt_cad', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
